### ISSUE TITLE
Digging out previous chat messages at time of user login

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_android#633] opened 2017-05-24 10:54 UTC
**Actual Behaviour**
Currently, if a user logins, their previous messages are not displayed. 

**Expected Behaviour**
At every login, fetch the old chat messages and display them.

**Steps to reproduce it**
We have a new memory servlet which will help. The previous conversation log is returned in a cognitions object.

**Comment by mayank408** [comment] 2017-05-25 11:18
I would like to work on this, but before that want some discussion so that I could be clear how to achieve this. @mariobehling @DravitLochan @chirag15 @betterclever

**Comment by chiragw15** [comment] 2017-05-25 12:29
@mayank408 completed it last night. Sorry, didn't inform you earlier. I used a dialog box asking user if he wants to retrieve his old message.  If he clicked yes, simply got his old messages using memory.json and added it to database.

**Comment by mayank408** [comment] 2017-05-25 12:30
@chiragw15 ok, but pls first get assigned it to yourself so that co-developers don't work on the same thing.

**Comment by chiragw15** [comment] 2017-05-25 12:35
@mayank408 I thought you were working on #96 based on your today's scrum. Never mind,  will comment next time on the issue :+1:

**Comment by mayank408** [comment] 2017-05-25 13:14
@chiragw15 I was working on it but you already sent the pr for #96  , the problem is that is need some improvement as is does not like a table but a list.

**Comment by chiragw15** [comment] 2017-05-25 13:19
@mayank408 The table response was changed after I send that PR. Checkout the issue( #96 ) for new response. I should probably close that PR. It is of no use now. You can work on that issue.

**Comment by mayank408** [comment] 2017-05-25 13:21
@chiragw15 Ok please close the pr and I will get it assigned to myself . Cheers 👍

**Closed** 2017-05-29 18:15 UTC
