### ISSUE TITLE
Bad UI 

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susi_android#1769] opened 2018-11-13 14:32 UTC
When click on setting or about effects created on button (hover color) create abox type on button with rectangle shape except on text of button 

Please see gif completely for better understanding 
![20181114_022017](https://user-images.githubusercontent.com/34541684/48442449-2f4cdb00-e786-11e8-9526-bea6dc93a26e.gif)

**Comment by iamareebjamal** [comment] 2018-11-13 16:09
No idea what you are talking about. Please follow issue template and provide screenshots

**Comment by iamareebjamal** [comment] 2018-11-13 16:10
/remind me to close the issue in 2 days

**Comment by subhahu123** [comment] 2018-11-13 20:55
@iamareebjamal  updated with gif see it complete
There are various  ui bug and error

**Comment by iamareebjamal** [comment] 2018-11-13 21:49
Not a bug in the app. This is normal behavior on Android. Try any other app

**Comment by iamareebjamal** [comment] 2018-11-13 21:50
> There are various ui bug and error

Can't spot one error or bug

**Comment by subhahu123** [comment] 2018-11-13 21:51
I suggest u to see complete gif
When i click on setting see the box created

**Comment by subhahu123** [comment] 2018-11-13 21:56
> Not a bug in the app. This is normal behavior on Android. Try any other app

Compare with this
![20181114_032500](https://user-images.githubusercontent.com/34541684/48445642-f5cc9d80-e78e-11e8-88da-cf1171ce05b0.gif)

**Comment by subhahu123** [comment] 2018-11-13 21:57
@iamareebjamal 
I dont why u r not seeing

**Comment by iamareebjamal** [comment] 2018-11-13 21:59
Yup, "Not a bug in the app. This is normal behavior on Android. Try any other app"

We have not written any special code to make the box highlight. We are using standard Android Menu Items. If you think this is a bug in the app, try any other app and you should find the same behavior. If you do want to file the bug, there is an issue tracker for AOSP. You'll have better luck there.

However, if you do want to solve this issue, you are free to send a PR, however from our side, it's a `wontfix`

**Comment by subhahu123** [comment] 2018-11-13 21:59
If u think there is no error then u must ask others to have a look on
this.......................

**Closed by iamareebjamal** 2018-11-13 21:59 UTC
Labels: reminder, waiting-for-status, wontfix
