### ISSUE TITLE
Not getting Web search result

### ISSUE THREAD

**Issue by STS30** [fossasia/susi_android#1796] opened 2018-12-07 19:19 UTC
**Actual Behaviour**

Web Search result is not getting displayed

**Expected Behaviour**

Either a web search result summary should be displayed or at least a link of the search should be provided

**Steps to reproduce it**

Ask Susi to search anything 
For Example: Ask "What is Google?"

**Screenshots of the issue**

![screenshot_2018-12-08-00-55-27-880_ai susi](https://user-images.githubusercontent.com/45697885/49668527-79bf3000-fa84-11e8-952c-8f62cbe0aa31.png)

**Comment by iamareebjamal** [comment] 2018-12-09 17:39
Duplicate of #1758

**Closed by iamareebjamal** 2018-12-09 17:39 UTC
