### ISSUE TITLE
Adding photo upload feature

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_android#461] opened 2017-01-10 19:16 UTC
**Actual Behaviour**

Currently there is no option to add photo uploads, cropping and marking tools and send them in the app.

**Expected Behaviour**

We can add this feature as many app have this feature to add photo from camera , edit it and send it.

**Steps to reproduce it**

We can add two activities:
- PhotoSendActivity to crop captured image and/or upload photo.
- PhotoEditActivity to allow drawing on captured image and upload this edited photo.

**Would you like to work on the issue?**

Yes i would love to work on this issue.

**Comment by betterclever** [comment] 2017-01-10 19:20
@saketkumar95 The issue is pointless in current context since susi server doesn't support image handling. I am not able to understand what are you trying to achieve. Please elaborate and discuss in Gitter channel first.  Thanks.

**Comment by mayank408** [comment] 2017-01-10 19:27
@betterclever is right . @saketkumar95 The server server is still incapable of handling images. So there is no point of raising such issues , Instead try to solve the existing issues. Thanks :)

**Comment by saketkumar95** [comment] 2017-01-10 19:41
@betterclever @mayank408 If susi server is not capable of handling images then we can raise this issue in the susi server too. Waiting for what? And as for now we can add this feature in the app too.

**Comment by Abhi2424shek** [comment] 2017-01-19 08:27
@saketkumar95 updates?

**Comment by jig08** [comment] 2017-01-19 08:38
@Abhi2424shek No updates required here, Thanks.

**Comment by mariobehling** [comment] 2017-01-19 11:45
Thanks for this thought. Implementing features like this depends on more developers engaging in Susi. As stated above this issue is not relevant in the Android app currently. Closing it therefore.

**Closed by mariobehling** 2017-01-19 11:45 UTC
Labels: Priority: Low (Delay for now)
