### ISSUE TITLE
Add search bar in Skills Activity

### ISSUE THREAD

**Issue by Nirvan101** [fossasia/susi_android#1078] opened 2017-12-16 13:40 UTC
**Actual Behaviour**
There is no search bar in skills activity. The user has to manually scroll through the list of activities to find the desired one.

**Expected Behaviour**
A search bar should be present to allow the user to search for a particular activity.

**Steps to reproduce it**
Open the skills activity page.

**LogCat for the issue**
NA

**Would you like to work on the issue?**
Yes

**Comment by srv-twry** [comment] 2017-12-23 10:02
@Nirvan101 Before creating please do check if there is an existing issue already created in the project.
Possible duplicate of #1035

**Closed** 2018-01-21 16:10 UTC
