### ISSUE TITLE
SUSI search results do not work

### ISSUE THREAD

**Issue by qualitytrash** [fossasia/susi_android#1802] opened 2018-12-09 15:44 UTC
**Actual Behaviour**

When SUSI attempts to pull up a search result, nothing is shown. (See below at screenshots)

**Expected Behaviour**

Should normally show a search result when SUSI searches something for the user.

**Steps to reproduce it**

(1) Launch SUSI without signing in
(2) Type in a question, like "what is SUSI?"

**Screenshots of the issue**

![smartselect_20181209-104121_susiai](https://user-images.githubusercontent.com/44712981/49699438-34dbec00-fb9f-11e8-94e5-ce7afd24a047.jpg)

**Would you like to work on the issue?**

Available for anyone

**Comment by iamareebjamal** [comment] 2018-12-09 17:35
Duplicate of multiple similar issues

**Closed by iamareebjamal** 2018-12-09 17:35 UTC
