### ISSUE TITLE
Keyboard does  not appear when search bar is tapped

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1372] opened 2018-06-09 07:51 UTC
**Actual Behaviour**

Currently, if we click the search icon, the keyboard appears. Now, if we press the back button, the keyboard hides. Now, if we want to continue typing, we require the keyboard. So, we tap the search bar as usual. But, now the keyboard does not appear.

**Expected Behaviour**

The keyboard should appear, if not already visible, if the user taps on the search bar.

**Steps to reproduce it**

* Open the skills list.
* Tap the search icon.
* Press back button.
* Now, tap the search bar.
You will see that the keyboard does not appear again.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment] 2018-06-09 10:13
Can't reproduce, working fine for me! @batbrain7 Confirm

**Comment by codedsun** [comment] 2018-06-09 10:15
The problem I m facing is that, 
1. Open the skills list,
2. Tap the search icon
3. Tap the cross icon

Keyboard doesn't closes. Please check this and ping me if I can take this issue!

**Comment by batbrain7** [comment] 2018-06-10 02:55
@arundhati24 in the third step after I tap on the search bar, the keyboard seems to pop up in my device, but not sure if only google keyboard pops up or other device specific keyboards pop up too.

**Comment by batbrain7** [comment] 2018-06-10 02:57
@codedsun I tried working on the issue @arundhati24 suggested to keep it that way because it follows what is done in the standard apps

**Comment by liveHarshit** [comment] 2018-12-14 14:07
@arundhati24 Keyboard is opening on double tap.

**Comment by liveHarshit** [comment] 2018-12-14 14:10
> The problem I m facing is that,
> 
> 1. Open the skills list,
> 2. Tap the search icon
> 3. Tap the cross icon
> 
> Keyboard doesn't closes. Please check this and ping me if I can take this issue!

Yes, it is an issue. Can I open a new issue for this and send a PR.

**Comment by immadisairaj** [comment] 2019-02-13 15:58
@batbrain7 
I don't see any kind of issue regarding this.
I think this is because the "Search Skill" is wrapped and when we tap just left of cross icon the keyboard doesn't appear.
The solution for this is just making it match with parent.
If this is ok. I will make a PR and close this ??

**Closed** 2019-02-16 02:54 UTC
