### ISSUE TITLE
Error message comes in the chat bubble

### ISSUE THREAD

**Issue by mejariamol** [fossasia/susi_android#306] opened 2016-10-25 19:33 UTC
**Actual Behaviour**

Error message comes in the chat bubble

**Expected Behaviour**

Should not come in the chat bubble. Instead should appear in toast or snackbar

**Screenshots of the issue**

![take4](https://cloud.githubusercontent.com/assets/13533840/19701184/20d5e0f6-9aaf-11e6-8246-3eb9e3841f1b.png)

**Would you like to work on the issue?**

yes

**Comment by jig08** [comment] 2016-10-26 05:53
Yes, and by the way we are preferring snackbar over toasts.

**Comment by mariobehling** [comment] 2016-10-26 08:22
Before solving this error we need to understand, where this error message comes from. The backend does not create this error message. Please provide more details about this message and its origina before solving it. Thank you.

**Comment by amitiwary999** [comment] 2016-10-26 12:59
@mariobehling this error is thrown by

catch (IndexOutOfBoundsException | NullPointerException e) {
                                        Log.d(TAG, e.getLocalizedMessage());
                                        answer = getString(R.string.error_occurred_try_again);
                                        ismap = false;
                                        isHavingLink = false;
                                    }
and the reason is:
Problem accessing /susi/chat.json. Reason:
    Invalid access token

**Comment by mejariamol** [comment] 2016-10-26 13:22
@amitiwary999  do u wanna solve dis issue ?

**Comment by amitiwary999** [comment] 2016-10-26 17:07
I will try.

**Comment by mayank408** [comment] 2016-10-26 17:16
@amitiwary999 @mariobehling 

if (!isNetworkConnected()) {
                                        recyclerAdapter.hideDots();
                                        nonDeliveredMessages.addFirst(new Pair(query, id));
                                        Snackbar snackbar = Snackbar.make(coordinatorLayout,
                                                getString(R.string.no_internet_connection), Snackbar.LENGTH_LONG);
                                        snackbar.show();
                                    } else {
                                        realm.executeTransactionAsync(new Realm.Transaction() {
                                            @Override
                                            public void execute(Realm bgRealm) {
                                                long prId = id;
                                                try {
                                                    ChatMessage chatMessage = bgRealm.where(ChatMessage.class).equalTo("id", prId).findFirst();
                                                    chatMessage.setIsDelivered(true);
                                                } catch (Exception e) {
                                                    e.printStackTrace();
                                                }
                                            }
                                        });
                                        rvChatFeed.getRecycledViewPool().clear();
                                        recyclerAdapter.notifyItemChanged((int) id);
                                        addNewMessage(getString(R.string.error_occurred_try_again), false, false, false, null);
                                    }
                                }

This is also a reason why the error is coming.

**Comment by mariobehling** [comment] 2016-10-27 03:21
Ok, thanks. The problem with this message is, that we don't know why it shows up. At this stage of the app development, we need to show the real reason for errors. "There was an error is not sufficient."

**Comment by mariobehling** [comment] 2016-10-27 03:33
Closing this in favor of https://github.com/fossasia/susi_android/issues/309

**Closed by mariobehling** 2016-10-27 03:33 UTC

**Comment by Orbiter** [comment] 2016-10-27 03:52
Wait a moment, https://github.com/fossasia/susi_android/issues/309 would not solve this. As the problem is caused by an invalid access token I believe the token must be renewed in some way. Maybe the token is void when the susi_server restarts.

Question: does the android client has still the log-in information and is able to retrieve a new access token automatically in that case? That would be the most appropriate solution for the problem.

**Comment by mariobehling** [comment] 2016-10-27 11:09
@Orbiter Thank you. As this issue is not related to the chat UI I opened a dedicated issue here: https://github.com/fossasia/susi_android/issues/311
