### ISSUE TITLE
Doesn't repond correctly

### ISSUE THREAD

**Issue by chamodperera** [fossasia/susi_android#2405] opened 2019-12-09 14:15 UTC
- **Susi doesn,t respond correctly when using without sign up**

- **For example below photo shows that susi calls itself with two names**

![Screenshot_20191209-190031 1](https://user-images.githubusercontent.com/39716499/70442431-57f3f100-1abc-11ea-83cc-595557221f4d.png)

**Comment by iamareebjamal** [comment] 2019-12-09 17:48
Duplicate of #2404

**Closed as completed by iamareebjamal** 2019-12-09 17:48 UTC
