### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by anujji1999** [fossasia/susi_android#1762] opened 2018-11-11 13:57 UTC
**Actual Behaviour**
lint-gradle-api.jar file is missing

![image](https://user-images.githubusercontent.com/33349650/48313832-ccbdd880-e5e7-11e8-8ba8-d21634215b91.png)

**Expected Behaviour**

Project should sync properly

**Would you like to work on the issue?**
Open for all

**Comment by anujji1999** [comment] 2018-11-11 14:01
@batbrain7 @iamareebjamal @arundhati24

**Comment by iamareebjamal** [comment] 2018-11-11 14:31
This is JCenter issue. Try again after some time. Not related to project. 

Re-Open if you are still unable to build after a few hours

**Comment by anujji1999** [comment] 2018-11-11 17:38
Tried 3-4 times.
Also tried reopening android studio.

**Comment by iamareebjamal** [comment] 2018-11-11 18:35
Duplicate of #1755

**Comment by iamareebjamal** [comment] 2018-11-11 19:07
Try now after fetching

**Closed** 2018-11-11 19:07 UTC
Labels: duplicate
