### ISSUE TITLE
When ask where is country/city

### ISSUE THREAD

**Issue by alvinindra** [fossasia/susi_android#1799] opened 2018-12-09 06:43 UTC
**Actual Behaviour**
When i ask "Where is Bali, Indonesia ?" the app send a empty message and the map.

**Expected Behaviour**
I hope that in the future this app can provide convenience in finding various cities or countries

**LogCat for the issue**
In input the questions or any message.
There i input the questions.
-> Test via questions

**Screenshots of the issue**
![the issue](https://user-images.githubusercontent.com/30944414/49694198-4087dc80-fbb8-11e8-9017-12b87da7033a.jpeg)

**Would you like to work on the issue?**
No sorry - Would like to further test this application and suggest further improvements.

**Comment by iamareebjamal** [comment] 2018-12-09 17:36
Duplicate of #1793

**Closed by iamareebjamal** 2018-12-09 17:36 UTC
