### ISSUE TITLE
Susi v1.1.0; The app crashes when I asked some questions.

### ISSUE THREAD

**Issue by HarryHeights** [fossasia/susi_android#2239] opened 2019-05-31 15:23 UTC
**Describe the bug**
The app crashed when I tried to ask certain questions. I don't the questions are the cause of the crash though. But the app mostly crashed when I asked who the President of my country was.

**Expected Behaviour**
If the AI had knowledge of who my President is(it does have that information), I expected it to reply me with the answer. It did though, but the app had crashed.

**Steps to reproduce it**

1. Ensure app process isn't running in the background.
2. Launch app.
3. You could ask the same question I asked. "Who is the President of Nigeria?"

**Screen recording**
https://youtu.be/hTnpa4mpeAM

**Test Environment:**
Device: Redmi Note 5 Pro
OS: Android 8.1.0
Software version: Susi v1.1.0

**Would you like to work on the issue?**
I don't have the technical know-how to work on the issue.

**Logcat**

```
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{b207293 position=37 id=-1, oldPos=-1, pLpos:-1 no parent} android.support.v7.widget.RecyclerView{faccb82 VFED.V... .F....ID 0,0-1080,1931 #7f0900fe app:id/rv_chat_feed}, adapter:org.fossasia.susi.ai.chat.adapters.recycleradapters.ChatFeedRecyclerAdapter@ac32e4f, layout:android.support.v7.widget.LinearLayoutManager@d50f9dc, context:org.fossasia.susi.ai.chat.ChatActivity@6a3c1b
	at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
	at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8317)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1571)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:597)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1858)
	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
	at android.view.Choreographer.doCallbacks(Choreographer.java:841)
	at android.view.Choreographer.doFrame(Choreographer.java:769)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

```

**Comment by atm1504** [comment] 2019-05-31 15:46
@HarryHeights please recheck it. I tried to reproduce it but the app did not crash.  It's working fine irrespective of the method of input (voice or type).

**Comment by atm1504** [comment] 2019-06-01 05:43
@HarryHeights I don't think its because susi does not have the answer. Susi has the answer to this question. Also if susi don't know any answer it says that it has not been trained to answer the question. Please check in more detail. The app is crashing because of some other problem.

**Comment by HarryHeights** [comment] 2019-06-01 07:54
Yea @atm1504 . I really dunno what's causing the problem. But it's happening anyway. It just happens.

**Comment by atm1504** [comment] 2019-06-01 07:58
@HarryHeights please try building the app from the development branch and check if the error still exists for you or not.

**Comment by HarryHeights** [comment] 2019-06-01 08:06
I have zero development skills. I'm just a content creator.

**Comment by realrufans** [comment] 2019-06-01 12:05
I downloaded it from F-Droid and I was able to reproduce this.


I will download the git into my AS to see if it will crash with my emulator (Android 9)

**Comment by atm1504** [comment] 2019-06-04 13:48
@iamareebjamal it can easily be resolved after #2247 is merged.

**Comment by iamareebjamal** [comment] 2019-06-04 15:12
How is that related to this issue?

**Comment by atm1504** [comment] 2019-06-04 15:17
There is some fault in establishing the system of passing the voice command to the chat activity. What the app treats is that it executes the code twice, once as a query parameter and the other time as an undelivered message. So, sometimes we are getting multiple response. This is leading to the crash of the app.

**Comment by atm1504** [comment] 2019-06-05 14:33
@iamareebjamal I hope this issue will resolve after https://github.com/fossasia/susi_android/pull/2236 is merged.

**Comment by atm1504** [comment] 2019-07-11 14:18
@mariobehling @iamareebjamal I can no longer reproduce this issue. Please close it.

**Closed** 2019-07-11 14:48 UTC
Labels: Priority: HIGH, bug
