### ISSUE TITLE
App crash in chatActivity

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1299] opened 2018-05-26 03:49 UTC
**Actual Behaviour**

Sometimes when we click on the Try it button in skillsDetails fragment it moves back to the chatactivity and the app crashes.

**Expected Behaviour**

The app should not crash. the last line the logcat is the reason for the crash

**Steps to reproduce it**

Login to the app, open chat activity,click on the susi button at the top right and then choose any skill and click on it.

**LogCat for the issue**

![screen shot 2018-05-25 at 5 43 35 pm](https://user-images.githubusercontent.com/16780496/40572299-e4669adc-60c5-11e8-9e64-a06af0b5d409.png)

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment] 2018-06-06 04:36
I would like to work on this issue

**Comment by batbrain7** [comment] 2018-07-13 17:29
@codedsun please provide the necessary information you have for this issue here ? it may be helpful so that this can be rectified

**Comment by batbrain7** [comment] 2018-07-13 20:17
#964 this is the similar issue that we have related to hotword detection which shows a log cat of segmentation fault.
@iamareebjamal could you please help in this , I am unable to understand the log messages

**Comment by iamareebjamal** [comment] 2018-07-13 22:23
This isn't easy to debug, it doesn't throw any exception so there is no stack trace

**Comment by varunon9** [comment] 2018-12-16 10:55
This issue is reproducible on my device Xiaomi Redmi 4A.
Steps-
1. From Chat screen go to Skills screen by clicking on skills button
2. Select any skill e.g. Anagrams
3. Click on Try-It button
4. You will be redirected back to Chat screen and then app will crash with following logs-
```
12-16 16:21:11.884 21957-21957/ai.susi D/ActivityThreadInjector: clearCachedDrawables.
12-16 16:21:11.993 21957-21957/ai.susi D/LinkPreviewViewHolder: 205: onPos: Anagram Solver - solves any anagram!
12-16 16:21:11.994 21957-21957/ai.susi D/LinkPreviewViewHolder: 217: handleItemEvents: isEmpty
12-16 16:21:12.056 21957-21957/ai.susi D/LinkPreviewViewHolder: 205: onPos: Anagram Solver - solves any anagram!
12-16 16:21:12.058 21957-21957/ai.susi D/LinkPreviewViewHolder: 217: handleItemEvents: isEmpty
12-16 16:21:12.100 21957-21957/ai.susi I/TextToSpeech: Sucessfully bound to com.google.android.tts
12-16 16:21:12.139 21957-21957/ai.susi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@75ca55a
12-16 16:21:12.139 21957-21957/ai.susi V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a70038b
12-16 16:21:12.150 21957-22209/ai.susi D/OkHttp: --> GET https://api.susi.ai/susi/chat.json?device_type=Android&country_name=&country_code=&timezoneOffset=-330&longitude=77.67960566&q=Anagram%20for%20best&latitude=12.94543579&language=en&geosource=gps&access_token=dHfLbdlP9sA17z5WSo7UcDzxkBIIDt
12-16 16:21:12.150 21957-22209/ai.susi D/OkHttp: --> END GET
12-16 16:21:12.278 21957-21957/ai.susi A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x727574786574e0 in tid 21957 (ai.susi)
```
Last line is responsible for crash. 
Open the app again. Since the bot failed to provide response due to crash, it will try try again. Then app will crash 2nd time with following logs-
```
12-16 16:24:55.936 22586-22715/ai.susi I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
12-16 16:24:55.988 22586-22586/ai.susi D/LinkPreviewViewHolder: 205: onPos: Anagram Solver - solves any anagram!
12-16 16:24:55.989 22586-22586/ai.susi D/LinkPreviewViewHolder: 217: handleItemEvents: isEmpty
12-16 16:24:56.010 22586-22586/ai.susi D/AndroidRuntime: Shutting down VM
12-16 16:24:56.010 22586-22586/ai.susi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.susi, PID: 22586
    java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{e3bcf8f position=36 id=-1, oldPos=-1, pLpos:-1 not recyclable(0) no parent} android.support.v7.widget.RecyclerView{597db27 VFED.V... .F....ID 0,0-720,1114 #7f0900fa app:id/rv_chat_feed}, adapter:org.fossasia.susi.ai.chat.adapters.recycleradapters.ChatFeedRecyclerAdapter@d9861d4, layout:android.support.v7.widget.LinearLayoutManager@5a86f7d, context:org.fossasia.susi.ai.chat.ChatActivity@401555f
        at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
        at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
        at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8317)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1571)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:597)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1858)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
        at android.view.Choreographer.doFrame(Choreographer.java:605)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:5523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
12-16 16:24:56.012 22586-22586/ai.susi E/MQSEventManagerDelegate: failed to get MQSService.
12-16 16:24:56.025 22586-22586/ai.susi I/Process: Sending signal. PID: 22586 SIG: 9
```

**Comment by vkk2018** [comment] 2019-01-05 06:43
I want to work on this issue

**Comment by arundhati24** [comment] 2019-04-11 10:57
I think this issue has already been fixed. @atm1504 @Bhavnaharitsa Could you please verify this once?

**Comment by Bhavnaharitsa** [comment] 2019-04-11 12:03
@arundhati24 As of the current status of the app, all skills lead to their respective pages and on clicking " try it " they work fine. This is an older issue and I think was resolved way back.

**Comment by Bhavnaharitsa** [comment] 2019-04-11 12:16
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/37215508/55956419-8c8b8080-5c81-11e9-9f71-85e1173a329f.gif)

**Comment by arundhati24** [comment] 2019-04-11 16:03
Yes, this was resolved. Just wanted to make sure this does not exist anymore. Thanks. There are many issues like this that need to be closed now. Closing this.

**Closed by arundhati24** 2019-04-11 16:03 UTC
Labels: help wanted
