### ISSUE TITLE
App crashes after logout 

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#742] opened 2017-06-20 05:40 UTC
**Actual Behaviour**

App is crashing after logout 

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

logout from app. Login and logout 

**LogCat for the issue**

Process: org.fossasia.susi.ai, PID: 29039
                                                                      java.lang.IllegalStateException: Realm instance has been closed or this object or its parent has been deleted.
                                                                          at io.realm.RealmList.checkValidView(RealmList.java:754)
                                                                          at io.realm.RealmList.size(RealmList.java:548)
                                                                          at org.fossasia.susi.ai.adapters.recycleradapters.WebSearchAdapter.getItemCount(WebSearchAdapter.java:111)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3416)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2963)
                                                                          at android.view.View.measure(View.java:17438)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                          at android.view.View.measure(View.java:17438)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8456)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:570)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                                          at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1593)
                                                                          at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4625)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5233)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                          at io.realm.internal.UncheckedRow.nativeSetLink(Native Method)
                                                                          at io.realm.internal.UncheckedRow.setLink(UncheckedRow.java:241)
                                                                          at io.realm.ChatMessageRealmProxy.realmSet$webLinkData(ChatMessageRealmProxy.java:498)
                                                                          at org.fossasia.susi.ai.model.ChatMessage.setWebLinkData(ChatMessage.java:54)
                                                                          at org.fossasia.susi.ai.adapters.recycleradapters.ChatFeedRecyclerAdapter$7.onPos(ChatFeedRecyclerAdapter.java:652)
                                                                          at com.leocardz.link.preview.library.TextCrawler$GetCode.onPostExecute(TextCrawler.java:64)
                                                                          at com.leocardz.link.preview.library.TextCrawler$GetCode.onPostExecute(TextCrawler.java:43)
                                                                          at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                          at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                          at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5233)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment] 2017-06-22 21:15
Not able to reproduce it. @amitiwary999 Either mention the exact way to reproduce the crash else close this issue.

**Comment by amitiwary999** [comment] 2017-06-27 21:45
@chiragw15 app crashes in case of rss action type reply. After login if your last message is rss action type and logout instantly app crashes. So step is ask some question for rss action type reply then logout after that login and logout as soon as possible. Reason for crash is after logout realm closed but linkpreview still running in background and it try to change real object but realm is already closed.

**Closed** 2017-07-04 02:27 UTC
Labels: bug
