### ISSUE TITLE
Crash on cancelling speech input

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#657] opened 2017-06-03 16:39 UTC
**Actual Behaviour**

App crashes if speech input is enabled and then disabled

**Expected Behaviour**

The app should not crash

**Steps to reproduce it**

Go to chat screen, click on the microphone icon to enable speech input, then click on cross icon, the app crashes

**LogCat for the issue**

````
java.lang.IllegalArgumentException: Service not registered: android.speech.SpeechRecognizer$Connection@fb3c905
  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
  at android.app.ContextImpl.unbindService(ContextImpl.java:1511)
  at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
  at android.speech.SpeechRecognizer.destroy(SpeechRecognizer.java:408)
  at org.fossasia.susi.ai.activities.MainActivity.cancelSpeechInput(MainActivity.java:257)
  at org.fossasia.susi.ai.activities.MainActivity_ViewBinding$1.doClick(MainActivity_ViewBinding.java:44)
  at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
  at android.view.View.performClick(View.java:5609)
  at android.view.View$PerformClick.run(View.java:22259)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

````

**Would you like to work on the issue?**

No

**Comment by amitiwary999** [comment] 2017-06-03 17:03
@iamareebjamal I tried it but app is not crashing in my case.can you tell me exact step?

**Comment by iamareebjamal** [comment] 2017-06-03 17:14
![](https://im3.ezgif.com/tmp/ezgif-3-32d8ad45f5.gif)

**Comment by iamareebjamal** [comment] 2017-06-03 17:14
Happening continously

**Comment by chiragw15** [comment] 2017-06-04 01:26
Though I was not able to reproduce the crash but I found something similar on stackoverflow https://stackoverflow.com/questions/13227105/speechrecognizer-not-connected-to-recognition-service.
#661 should prevent the crash.

**Comment by mayank408** [comment] 2017-06-12 02:57
It is merged 👍

**Closed by mayank408** 2017-06-12 02:57 UTC
Labels: bug
