### ISSUE TITLE
Inappropriate answers and Web search link not provided

### ISSUE THREAD

**Issue by Circinusss** [fossasia/susi_android#1759] opened 2018-11-04 15:27 UTC
**Issues Faced**

While testing the AI i noticed it wasn't giving appropriate answers to certain questions. The answer given by the AI would be totally different from the question.
Also noticed that there are no link(s) provided when the AI says "Here's a web search".
Atleast one link should be present, but nothing is seen.
Sometimes for certain queries the AI seems to be monotonous as it has a fixed reply phrase for a particular question. The AI could have different reply phrases to make it more interesting.

Rest didn't notice any lags or instability in the UI. The app is quiet stable. The developers have done a great job.

**Screenshots of the issue**
![screenshot_20181104-203439](https://user-images.githubusercontent.com/44549551/47966058-1e101a00-e074-11e8-9871-535562599112.png)

Hope these issues are fixed soon.🙂

**Comment by iamareebjamal** [comment] 2018-11-04 18:00
Duplicate of previous unrelated issues

**Closed by iamareebjamal** 2018-11-04 18:00 UTC
