### ISSUE TITLE
Not so efficient

### ISSUE THREAD

**Issue by hardiksethi08** [fossasia/susi_android#1750] opened 2018-10-30 08:40 UTC
**Not giving answers to many of the asked questions**

**I expected a correct reply**

**

![Uploading Screenshot_2018-10-30-13-48-18-485_ai.susi.png…]()

**

**Comment by iamareebjamal** [comment] 2018-10-30 10:03
Off Topic and maybe duplicate of #1749 

Also, this is not a problem of Android Client

**Closed by iamareebjamal** 2018-10-30 10:03 UTC
