### ISSUE TITLE
SUSI.AI problems

### ISSUE THREAD

**Issue by rkstlohchab** [fossasia/susi_android#1753] opened 2018-10-30 14:23 UTC
**Actual Behaviour**
When i asked some question to susi it give unexpected answers 
For example - i asked that define frequency and it give answer that absolutely frequency
another question that asked is what is whatsapp it give answer here is a websearch result
but do not provide any info   

**Expected Behaviour**
I was expecting that in first question it will give definition of frequency and in other question i expected that i will answer that what is whatsapp

**LogCat for the issue**

when i am asking questions i crashes and closes app

**Screenshots of the issue**

![screenshot_susi ai_20181030-193036](https://user-images.githubusercontent.com/44434790/47724595-fccaba80-dc7c-11e8-8cac-85991d807b72.png)

**Comment by iamareebjamal** [comment] 2018-10-30 15:12
Duplicate of #1752

**Closed by iamareebjamal** 2018-10-30 15:12 UTC
