### ISSUE TITLE
(BUG)[susi_android Version 1.2.0 ] forgot password option is not working properly

### ISSUE THREAD

**Issue by XAMIR555** [fossasia/susi_android#2246] opened 2019-06-04 12:00 UTC
#### Project Information
* Repository--------------:[Here](https://github.com/fossasia/susi_android)
* Project Name----------:  [ SUSI.AI](https://play.google.com/store/apps/details?id=ai.susi&ah=dWLy7rQKg16yxp3OLlfGsqjnp8c)
* Publisher---------------:  [FOSSASIA ](https://github.com/fossasia)
* My GitHub account-----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I click the Forgot Password option, you may want to show more options where I can use my email address to get my account passwords back.

#### Actual behavior

When clicking on the Forgot Password option, no response is displayed further no any opens are displayed.

#### How to reproduce
* open the application
* click on Forgot password 
* Note the Bug
 
* Browser/App version-:1.2.0
* Operating system----: 8.1.0

#### Recording Of The Bug

![20190604_164257](https://user-images.githubusercontent.com/49812927/58876886-2ec55480-8684-11e9-9b4f-de6de3429e33.gif)

**Comment by atm1504** [comment] 2019-06-04 13:11
@XAMIR555 it is not a bug. Here in this app, u need to enter the email first, after that if you press the forgot password, then a password resetting link is being sent in your email. So, the email is required to reset the password.

**Comment by atm1504** [comment] 2019-06-05 14:34
@iamareebjamal please close it.

**Closed** 2019-06-05 17:29 UTC
